# Generated by Django 2.2.13 on 2023-09-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreGames', '0003_auto_20230912_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechanacimiento',
            field=models.CharField(max_length=8),
        ),
    ]
