# Generated by Django 2.2.13 on 2023-09-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreGames', '0004_auto_20230915_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechanacimiento',
            field=models.DateField(),
        ),
    ]
