# Generated by Django 2.2.13 on 2023-09-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreGames', '0005_auto_20230915_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechanacimiento',
            field=models.CharField(max_length=8),
        ),
    ]
