# Generated by Django 2.2.13 on 2023-09-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreGames', '0009_categoria_detalle_producto_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='catergoria',
            new_name='categoria',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='STOREGAMES_PRODUCTO',
        ),
    ]
