# Generated by Django 2.2.13 on 2023-09-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreGames', '0013_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
