# Generated by Django 2.2.13 on 2023-09-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreGames', '0014_auto_20230930_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
